# Generated by Django 4.2.3 on 2023-07-29 21:14

from django.db import migrations, models
import nice_a.core.model_mixin


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('personal_photo', models.URLField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
            ],
            bases=(nice_a.core.model_mixin.StrFormFieldsMixin, models.Model),
        ),
    ]
